sudo: required
language: generic 

services:
    - docker
 
before_install:
    - docker build -t pvasisht/docker-react -f Dockerfile.dev .
  
script:
    - docker run -e CI=true pvasisht/docker-react npm run test
